### ISSUE TITLE
Set an active release.

### ISSUE THREAD

**Issue by oponder** [giantswarm/azure-operator#110]
There is currently no active versionbundle for the azure-operator.

This means non-admin users will not be able to create a cluster, and Happa is not able to suggest what Release Version a user should pick by default.

Is the current versionbundle done? If so we should change the WIP flag to false.

ping @kopiczko @r7vme

**Comment by r7vme** [comment]
@kopiczko i think we need this ASAP. can you take a look?

**Comment by oponder** [comment]
@r7vme we will need this at least before letting a customer attempt to use it.

Until then it's ok like this, since we are not comfortable with breaking the process.

I made a workaround so that at least we can create clusters using happa as an admin for now. That workaround is in progress, but you can see it here:

https://github.com/giantswarm/happa/issues/282

**Comment by kopiczko** [comment]
Can we close that? We'll have the release when it's needed.

**Comment by kopiczko** [comment]
Ping @oponder

**Comment by oponder** [comment]
Ok, we can close it. Let's not forget though ok!
