### ISSUE TITLE
Disks on master are not mounted sometimes

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#113]
etcd and docker disks are expected to be `sdc` and `sdd` respectevely.

master vm messed up disk naming once:
- OS disk became `sdc` 
- etcd disk became `sda`
- docker disk became `sdb`
- ephemeral (by default in Azure) became `sdd`

Node had following scsi attachments:
```
[1:0:0:0]    cd/dvd  Msft     Virtual CD/ROM   1.0   /dev/sr0 
[3:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sdc 
[4:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sda 
[4:0:0:1]    disk    Msft     Virtual Disk     1.0   /dev/sdb 
[5:0:1:0]    disk    Msft     Virtual Disk     1.0   /dev/sdd 
```

Node with right disk naming has `lscsi` output:
```
[1:0:0:0]    cd/dvd  Msft     Virtual CD/ROM   1.0   /dev/sr0 
[2:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sda 
[3:0:1:0]    disk    Msft     Virtual Disk     1.0   /dev/sdb 
[5:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sdc 
[5:0:0:1]    disk    Msft     Virtual Disk     1.0   /dev/sdd 
```

We probably need to find better way, to detect disks. Right now we rely on kernel disk names (e.g. `sdc`)

**Comment by r7vme** [comment]
hmm, acs-engine also hardcodes [disk name](https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetes_mountetcd.sh#L5). In general, we can not identify which disk for what, because block device is empty and does not contain any labels. Only proper way if Azure can put device labels, but this are only my dreams.

Ok, so this issue can not really be solved properly.

What we should do is to trigger immediate alert.

@JosephSalisbury if .mount unit failed will node-exporter detect that in guest cluster?

**Comment by r7vme** [comment]
@kopiczko please report here if you'll see .mount units failed in guest clusters. Thanks

**Comment by JosephSalisbury** [comment]
See https://github.com/giantswarm/g8s-prometheus/blob/master/helm/g8s-prometheus-chart/prometheus-rules/systemd.rules#L1

We get alerts on failed systemd units.

**Comment by JosephSalisbury** [comment]
But, guest cluster monitoring is not yet enabled in Azure, see https://github.com/giantswarm/giantswarm/issues/2372 for tracking

**Comment by r7vme** [comment]
Just hit this bug in host cluster on one of the workers

```
r7vme@worker2 ~ $ lsblk 
NAME    MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sdb       8:16   0 30.4G  0 disk  
|-sdb4    8:20   0    1G  0 part  
|-sdb2    8:18   0    2M  0 part  
|-sdb9    8:25   0 28.1G  0 part  /
|-sdb7    8:23   0   64M  0 part  
|-sdb3    8:19   0    1G  0 part  
| `-usr 254:0    0 1016M  1 crypt /usr
|-sdb1    8:17   0  128M  0 part  /boot
`-sdb6    8:22   0  128M  0 part  /usr/share/oem
sr0      11:0    1  662K  0 rom   
sdc       8:32   0   14G  0 disk  
`-sdc1    8:33   0   14G  0 part  /mnt/resource
sda       8:0    0  100G  0 disk  
r7vme@worker2 ~ $ 
```

**Comment by kopiczko** [comment]
I labelled it blocked. We need more input.

**Comment by kopiczko** [comment]
I don't think it makes sense to keep it opened. Nobody actively checks it. When it happens to not have disk unmounted we should be alerted about low disk space.

**Comment by r7vme** [comment]
This is still actual. We know how to fix this https://github.com/giantswarm/giantnetes-terraform/pull/123
