### ISSUE TITLE
No peering with host cluster

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#115]
At the moment guest clusters does not have network peering with host cluster, which is required for SSH and monitoring.

cc: @kopiczko

**Comment by xh3b4sd** [comment]
What is with this issue? IIRC Theo is working on it. Can we move this to WIP then?

**Comment by TheoBrigitte** [comment]
This issue is about providing network peering between host and guest cluster on azure, so we can reach into guest cluster from the host (e.g. ssh into guest master node).

And yes I am working on this.

**Comment by xh3b4sd** [comment]
Sweet. Thank you for checking back.

**Comment by r7vme** [comment]
Done as per @TheoBrigitte
