### ISSUE TITLE
use azure standard storage for default storage class

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#116]
right now default storage class uses Premium disks. We should use Standard disks:
1) Standard is cheaper than Premium
2) Standard is more universal as supported by all vm sizes

**Comment by kopiczko** [comment]
I understand standard is also super slow. Is it even viable? Do you mean for VM disks?

**Comment by r7vme** [comment]
> I understand standard is also super slow.

please forget it. It was misunderstanding from my side. Standard + unmanaged disk are super slow. Managed standard disk is fine.
