### ISSUE TITLE
reconcile deployments

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/azure-operator#119]
I tried to do that easy way. Problem is customData in VM templates can't be set on updates. Probably we should detect machines created, and leave deployments only for missing machines.

- [x] After it's done update `NodeConfigSpecGuestNode.Name` godoc in apiextensions. See https://github.com/giantswarm/apiextensions/pull/50#discussion_r166623756. (https://github.com/giantswarm/apiextensions/pull/52)

**Comment by kopiczko** [comment]
This is very important story for azure-operator. The azure operator doesn't reconcile ATM. It means it isn't production ready. I'm adding this story to the product board and I'd like to start to work on that if possible.

cc  @teemow

**Comment by othylmann** [comment]
You need to explain a bit better. Not production ready is fine, I just need to understand the problems / limitations that result from the challenge. :) 

I can explain anyone anything. 

ping @kopiczko

**Comment by kopiczko** [comment]
This basically means:

1. When there is an error during guest cluster creation the operator won't try to fix the problem (aka. reconcile towards desired state).
2. When VM goes down (master or worker), the operator won't try to recreate it (aka. ....)
3. (This is a minor thing) When someone tests the operator and deletes a *random thing, e.g. a load balancer - it won't be recreated by the operator.

* Not all resources will be safe to delete w/o consequences even if the operator reconciles correctly.

This is also prerequisite for workers scaling and cluster upgrades.

**Comment by teemow** [comment]
My first thought. Why wasn't this part of the Azure story in the first place? Why did we now prioritize something different for your team but have to go back the already closed Azure story? 

Something we can learn from I guess :)

Eg if the goal of a story is to get a customer and our website on Azure would that imply that this is production ready? I guess this wasn't clearly written down. We need to get better here from both sides. Defining the scope and goal of a story and communicate when it is actually done.

Btw we asked about the missing parts in the current Azure setup and the only thing that I heard was that service type=Loadbalancer doesn't work.

Besides all the meta stuff above:

> When VM goes down (master or worker), the operator won't try to recreate it (aka. ....)

Why does the operator manage a single vm? Isn't that done by the Azure ressource manager and/or scalesets?

> (This is a minor thing) When someone tests the operator and deletes a *random thing, e.g. a load balancer - it won't be recreated by the operator.

Similar. Will we reconcile all those resources individually? How is this done within the new cloudformation version of the AWS operator?

How much work do you expect this to be? Just roughly speaking. I am totally fine with reopening the azure operator story and adding a first basic reconciliation. Maybe this can then be extended within the upgrade story. And we would need to decide if scaling is also part of the initial feature set we want to have or not.

Thanks for bringing this up!

**Comment by xh3b4sd** [comment]
What about this issue? I feel like this is a dup of https://github.com/giantswarm/giantswarm/issues/2483. Can we close this then?

**Comment by kopiczko** [comment]
I'm not sure it's a dup. It's likely https://github.com/giantswarm/giantswarm/issues/2483 will cover this, but not 100%.

**Comment by xh3b4sd** [comment]
To me it looks like this issues is sorted. What is left? I would just close it.

**Comment by kopiczko** [comment]
It would be fixed by https://github.com/giantswarm/azure-operator/pull/213
Right now when deployments are created the operator won't call CreateOrUpdate again.

**Comment by xh3b4sd** [comment]
Ok I think I get you now. I will sort this soon.

**Comment by xh3b4sd** [comment]
IMO this is done now.
