### ISSUE TITLE
Add healthz endpoint that checks Azure API access

### ISSUE THREAD

**Issue by rossf7** [giantswarm/azure-operator#12]
The operator should have a healthz endpoint that checks the Azure API credentials are valid. If possible it should also validate that the operator has the correct API permissions.

The endpoint should be created in https://github.com/giantswarm/microendpoint so it can be reused.

- [ ] add check
- [ ] enable checks in helm charts

**Comment by xh3b4sd** [comment]
Hey guys. What about this issue? Sounds fairly simple. Lets pick it or rip it.

**Comment by rossf7** [comment]
Let's add the `healthz`. I'll take this week as boyscouting.
