### ISSUE TITLE
Azure public IP limit

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/azure-operator#163]
## What is the issue ?
We are currently limited to having 8 guest cluster on azure.
We hit the following error when trying to create a new guest cluster

```
{
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
                {
                        "code": "BadRequest",
                        "message": "{\r\n \"error\": {\r\n \"code\": \"StaticPublicIPCountLimitReached\",\r\n \"message\": \"Cannot create more than 20 public IP addresses with static allocation method for this subscription in this region.\",\r\n \"details\": []\r\n }\r\n}"
                }
        ]
}

```

## What is the reason ?
ARM static public ip allocation method is limitting us to 20 different public ip per subscription by default.
see https://github.com/giantswarm/azure-operator/blob/d3d0da704844bc0fa4e6b95e4fd5867136f9b9e5/service/azureconfig/v1/arm_templates/public_load_balancer_setup.json#L61

We also allocate 2 public ip per cluster (1 api + 1 ingress) and run 2 host cluster (gollum & godsmack).

## Solutions
* ARM static public ip quota limitation of 20 can be raised by opening a support request via Azure portal.

* Switching to ARM dynamic public ip allocation method which have a default limit of 60 ip per subscription.
see https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#networking-limits-1

* BYOC story should also by us some time since guest cluster would have the option to be created in a different subscription

slack discussion https://gigantic.slack.com/archives/C6H0T6W1X/p1521728701000437

**Comment by TheoBrigitte** [comment]
Tried to fix this issue by switching from static to dynamic IP 

But this did not work since dynamic IP are not allocated on creation and therefore prevent us to create a dns A record by referencing the created IP.

**Comment by TheoBrigitte** [comment]
We agreed to leave this issue for now. I am creating this to share knowledge for later reference.

**Comment by r7vme** [comment]
Should we close this ticket, as seems that it's standard quota/limit thing?

**Comment by TheoBrigitte** [comment]
Closing, as quota was raised and now have limit of 100 static public IPs.
