### ISSUE TITLE
Azure: No docker disks on vmss masters

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#231]
Master looks fine, because this error silently ignored.

```
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: dev-sdd.device: Job dev-sdd.device/start timed out.
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: Timed out waiting for device dev-sdd.device.
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: Dependency failed for Formats the disk drive.
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: Dependency failed for Mounts disk to /var/lib/docker.
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: var-lib-docker.mount: Job var-lib-docker.mount/start failed with result 'dependency'.
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: format-docker-disk.service: Job format-docker-disk.service/start failed with result 'dependency'.
Jun 11 10:20:22 8hpfx-master-000000 systemd[1]: dev-sdd.device: Job dev-sdd.device/start failed with result 'timeout'.
```

```
r7vme@8hpfx-master-000000 /etc/systemd/system $ lsblk 
NAME    MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda       8:0    0 30.4G  0 disk  
|-sda1    8:1    0  128M  0 part  /boot
|-sda2    8:2    0    2M  0 part  
|-sda3    8:3    0    1G  0 part  
| `-usr 254:0    0 1016M  1 crypt /usr
|-sda4    8:4    0    1G  0 part  
|-sda6    8:6    0  128M  0 part  /usr/share/oem
|-sda7    8:7    0   64M  0 part  
`-sda9    8:9    0 28.1G  0 part  /
sdb       8:16   0   16G  0 disk  
`-sdb1    8:17   0   16G  0 part  /mnt/resource
sdc       8:32   0   50G  0 disk  /var/lib/etcd
sr0      11:0    1  732K  0 rom   
```

**Comment by xh3b4sd** [comment]
Can you please provide more information here? Does that happen during cluster creation or during updates or scaling? Do we know the root cause? Why does the master look fine when the VMSS is missing a disk?

**Comment by r7vme** [comment]
this happening during creation, no idea on the root cause now. Master looks fine, because docker data stored on OS disk. Do not hesitate to escalate to product and get SRE assigned to this issue.

**Comment by xh3b4sd** [comment]
I started working on the master updates. I think some disk magic is broken there anyway. Did we actually ensure that master reboots do not cause data loss? I will get back to some SRE and maybe just you later on.

**Comment by r7vme** [comment]
Ok the reason is clear now, our worker and master configuration is the same in terms of disks. We have only one disk size 50GB. In worker it's mounted properly as docker disk, in master it's mounted as etcd disk.

https://github.com/giantswarm/azure-operator/blob/master/service/controller/v2/arm_templates/main.json#L350
