### ISSUE TITLE
Azure: allow to preserve etcd data while upgrades

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#238]
At the moment we use VMSS for master. In case VMSS all disks are invicible for user (impliciptly managed by VMSS)

WE have two options:
- still use vmss and use disk attachment feature https://github.com/Azure/azure-sdk-for-go/issues/944
- switch back to regular vms

**Comment by r7vme** [comment]
I've tried to define vmss with pre-created etcd disk and getting error

```
                        "dataDisks": [
                            {
                                "lun": "0",
                                "caching": "ReadWrite",
                                "createOption": "Attach",
                                "managedDisk": {
                                    "storageAccountType": "Standard_LRS",
                                    "id": "[resourceId('Microsoft.Compute/disks', 'EtcdDisk')]"
                                }   
                            }   
                        ]   
```

```
Deployment failed. Correlation ID: 514cc568-9b46-4013-bd42-7d7c7ef96ff1. {
  "error": {
    "code": "InvalidParameter",
    "target": "dataDisk.managedDisk.id",
    "message": "Parameter 'dataDisk.managedDisk.id' is not allowed."
  }
}
```

This is actually aligned with API [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets#VirtualMachineScaleSetDataDisk). There is only one way to attach pre-created etcd disk by issuing PUT request to particular VM as described [here](https://github.com/Azure/vm-scale-sets/tree/master/preview/disk).

It's really complicate things, so we need to wait until vmss created and then do GET (to grab existing disks) and then update with PUT.

I'm starting to evaluate option number two with regular vm.

**Comment by r7vme** [comment]
With regular VM workflow can be following:
1. Create master VM with attached (externally defined) etcd disk
2. On update. Stop/Delete VM via Azure API call (depending on which operation will be faster)
3. Apply ARM template

As a trick to not depend on existing VM removal (we only need VM to be stopped to use etcd disk) we can use randomly generated master VM name.

cc: @xh3b4sd @kopiczko

**Comment by xh3b4sd** [comment]
How would we manage a multi master setup at best? 

I am leaning towards trying to preserve the VMSS support for masters as well. The implications you described do not sound too complicated to me. I would like to at least try to attach a predefined volume to the master VMSS. 

Should we get Stuart into the discussion here for more MS feedback?

**Comment by kopiczko** [comment]
> In case VMSS all disks are invicible for user

I don't understand what are the consequences? What bad scenarios can happen in that case?

**Comment by r7vme** [comment]
> How would we manage a multi master setup at best?

For multi master things work different, we don't care about persistence, because data replicated between VMs.

> I don't understand what are the consequences? What bad scenarios can happen in that case

You just can not reattach the disk, if vmss rolls out this particular vm disk gone with VM. It's not reattachable. But we have solution for that and it's described [here](https://github.com/Azure/vm-scale-sets/tree/master/preview/disk)

**Comment by r7vme** [comment]
Ok, looks like i did some wrong opinions.

Actually we can do like that with vmss (probably that what's @kopiczko assumed initially).

vmss does not recreate VMs (like ASG in AWS does for example). With vmss we have two options:
- "upgrade" - this is totally useless for us as it does (if supported) some OS level upgrades. For me with CoreOS (after changing user_data in template) nothing happened.
- "reimage" - this is actually what we need. After reimage data disks preserved and you get latest user_data. And it done pretty quickly (~few minutes vs. vm detele-create that takes a while).

I'm continuing testing different paramters (e.g. change user_data, change vm size, use Automatic updates). But definitely we have good news already.

So finally it will look like this:
- apply latest template.
- call Azure API with reimage reuqest

**Comment by xh3b4sd** [comment]
Good insights. So AFAIK we call for "upgrade" with each reconciliation. Should we do the same with "reimage" then or would we then roll the machines all the time? Because this would not be what we want. Machines should only be rolled when there are actual changes to be applied.

**Comment by r7vme** [comment]
> So AFAIK we call for "upgrade" with each reconciliation

Ah, cool. We actually can switch to "Automatic" for masters and workers. Because "upgrade" does not really impact VM itself. So this just move "update" call from azure-operator to vmss itself.

https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets#UpgradePolicy

**Comment by r7vme** [comment]
> Should we do the same with "reimage" then or would we then roll the machines all the time? 

Yes. Here is the tricky part. It looks like we need to reimage masters and even workers. I need to check on `rollingUpgradePolicy`, but feels like it's only related to "upgrade" and nothing to do with "reimage", which we need.

**Comment by r7vme** [comment]
Before switching to "Automatic" we need to check few use cases:
- what happens with VM if `custom_data` changed - tested today, VM stays intact only metadata updated, so on next "reimage" new custom_data will be used
- what happens with VM if "vm size" changed - ?
- what happens with VM if "CoreOS image" changed - ?

**Comment by xh3b4sd** [comment]
My plain guess is that you just update the scale set model via "update" no matter what changes, the VMs stay untouched but changes get applied to VMs and thus they get rolled on "reimage".

**Comment by kopiczko** [comment]
I thought custom_data (cloudconfigs) changes are applied on "upgrade". I think I tested that.
Also when "reimage" preserves the data we don't need to switch to regular VMs, do we?

**Comment by r7vme** [comment]
> Also when "reimage" preserves the data we don't need to switch to regular VMs, do we?

No we don't, which is really good :)

> I thought custom_data (cloudconfigs) changes are applied on "upgrade". I think I tested that.

From what i've tested, only after "reimage" new custom_data picked up. I initially also thought that waagent will pick new data and apply on reboot for example, but it's not the case. Which is fine for us our nodes are ephemeral and we shold do "reimage" by design.

**Comment by kopiczko** [comment]
Cool. So this probably means we can do automatic upgrade and call reimage API instead of update API in the azure-operator.

**Comment by r7vme** [comment]
We actually need both and in following order: "upgrade" + "reimage". We talked with @xh3b4sd about that and looks like solution is to do all this in operator (because Azure does not support "reimage" orchestration). He will come with more details i think.

**Comment by r7vme** [comment]
I think we are fine here. We have vmss with etcd disk and data is preserved if we do "upgrade" and "reimage". Related fix done [here](https://github.com/giantswarm/azure-operator/pull/237).

Closing.
