### ISSUE TITLE
Grant read access to Key Vault for cluster nodes

### ISSUE THREAD

**Issue by rossf7** [giantswarm/azure-operator#24]
Each cluster node will need read access to the cluster's Key Vault to download the TLS certificates on startup. The  "accessPolicies": []` in the vault resource is currently empty.

https://github.com/giantswarm/azure-operator/blob/keyvault/service/arm_templates/certificates.json#L38

Once the templates for creating the cluster nodes are merged we need to grant permission here.

See https://azure.microsoft.com/en-us/blog/keep-credentials-out-of-code-introducing-azure-ad-managed-service-identity/

**Comment by kopiczko** [comment]
It's already done with MSI.
