### ISSUE TITLE
Azure: peering leftovers after e2e tests

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#262]
In `godsmack` we hit 50 peering limit (default 10). All peerings seems leftovers from e2e CI runs.

We need to find a root cause and fix it.

@rossf7 mentioned that we can use https://github.com/giantswarm/ci-cleaner

**Comment by rossf7** [comment]
@r7vme Thanks for cleaning this up. 

I'm not sure why these aren't being cleaned up. Maybe we need to delete the peering if the Circle job fails or is canceled? 

@fgimenez Mentioned there is already a ticket for this. https://github.com/giantswarm/giantswarm/issues/3457

**Comment by rossf7** [comment]
Also having support for this in ci-cleaner would be good. @r7vme Do you know which API calls we need to make?

**Comment by r7vme** [comment]
> Do you know which API calls we need to make?

Not really, but i think azure-operator does similar calls. Check it's code.

**Comment by r7vme** [comment]
Now after we switched to VPN , there are connections leftovers

![2018-07-25-12 08 57-screenshot](https://user-images.githubusercontent.com/1277504/43194802-90cb8816-9003-11e8-90a7-80c2426da075.png)

**Comment by MarcelMue** [comment]
Is this still a thing? AFAIK @TheoBrigitte made a lot of progress with the ci-cleaner for azure.

**Comment by r7vme** [comment]
Yes, fixed by https://github.com/giantswarm/ci-cleaner
