### ISSUE TITLE
Use azure-operator binary to download secrets from Key Vault

### ISSUE THREAD

**Issue by rossf7** [giantswarm/azure-operator#27]
Currently the operator runs a bash script in the cloudconfig that is triggered by a systemd unit. Doing retries in the bash script is not nice so we discussed adding this to the azure-operator binary. Since it already has the `azure-go-sdk`.

https://github.com/giantswarm/azure-operator/pull/26#discussion_r140488870

**Comment by rossf7** [comment]
@kopiczko @TheoBrigitte IIRC we are removing Key Vault from Azure. Is that correct? If so can we close this?

**Comment by kopiczko** [comment]
Correct.

**Comment by xh3b4sd** [comment]
🎉
