### ISSUE TITLE
VMs are not created until VPN gateway is created

### ISSUE THREAD

**Issue by r7vme** [giantswarm/azure-operator#311]
While testing `1.1.0` wip release, i've noticed that azure-operator does not try to create VMs (master/worker vmss resources) until initial deployment (includes VPN gateway) is not finished.

Problem that VPN gateway takes up to 45 minutes (in reality 20-30 minutes) to be created. We don't really blocked by VPN gateway imo as it's used by ops access and monitoring only.

**Comment by r7vme** [comment]
I think we either can move VPN gateway to separate ARM template or reasses the reason, why we postponing VMs creation.

**Comment by xh3b4sd** [comment]
@TheoBrigitte is working in this direction and he actually implemented this. Would be cool to check back here and see if we can improve the situation. I noticed the longer startup times and it would be nice to get it lower again.

**Comment by xh3b4sd** [comment]
It is not about the template but about the scheduling and execution of the operatorkit resource implementations and how they interfere. Since the VPN gateway resource got introduced the times went up a lot and I recall the deployment resource and/or the instance resource get locked or blocked due to that somehow. I am not in the details there, just thought you have a vision or something.

**Comment by xh3b4sd** [comment]
@r7vme for the future please create all issues in giantswarm/giantswarm so we have all the usual labels available. I was looking for this one and couldn't find it. 

@TheoBrigitte IIRC you said you wanted to address this in the scope of some other work you were doing. Can you say something about your timeline? Cluster creation taking super long is a blocker for all devs and everybody would greatly benefit from your work here.

**Comment by TheoBrigitte** [comment]
This is actually the next issue on my list. Will try to find some time for this next week, if not I will start after I am back from holiday on September 19th.

**Comment by xh3b4sd** [comment]
Is this still the next issue on your list? :D

**Comment by TheoBrigitte** [comment]
Nope, priority has shifted towards PMs.

I know this issue is a big paint point for azure-operator as it makes it very slow now to spin up tenant cluster.

**Comment by xh3b4sd** [comment]
How difficult can this be? Do you want to pair on it again?

**Comment by TheoBrigitte** [comment]
VPN gateway is now handled by the vpn resource which happens in parallel of other resources.
This brings down tenant cluster creation down to approx. 10mn.


```
# cluster created at 10:33:17
$ k --context giantswarm-godsmack get azureconfig -ndefault o9b05 -oyaml|yq -y -r '.status.cluster.conditions[]'
lastHeartbeatTime: '2018-12-21T10:33:17.026566'
lastTransitionTime: '2018-12-21T10:33:17.026566'
status: 'True'
type: Creating

# master node up at 10:42:59
$ k --context giantswarm-o9b05 get no o9b05-master-000000 -oyaml|yq -y -r '.status.conditions[5]'
lastHeartbeatTime: '2018-12-21T10:50:45'
lastTransitionTime: '2018-12-21T10:42:59'
message: kubelet is posting ready status
reason: KubeletReady
status: 'True'
type: Ready

# took 9mn 42s to bring the cluster up :)
```

**Comment by r7vme** [comment]
10 min - awesome results!!!

**Comment by jgsqware** [comment]
That huge man!
