### ISSUE TITLE
Ensure we do call azure-sdk Responder functions when needed to avoid memory leaks

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/azure-operator#320]
Follow up on: https://github.com/giantswarm/azure-operator/pull/302#discussion_r209548473

We found out that when calling Azure api using the sdk, responses bodies are not always implicitly closed and we sometimes need to explicitly call Responder. Not doing so would result in memory leaks (see linked issue)

example:
- `VirtualNetworkPeeringsClient .List` calls Responder implicitly
https://github.com/Azure/azure-sdk-for-go/blob/4e8cbbfb1aeab140cd0fa97fd16b64ee18c3ca6a/services/network/mgmt/2018-06-01/network/virtualnetworkpeerings.go#L264-L285

- `VirtualNetworkPeeringsClient .Delete` does not calls Responder implicitly
https://github.com/Azure/azure-sdk-for-go/blob/4e8cbbfb1aeab140cd0fa97fd16b64ee18c3ca6a/services/network/mgmt/2018-06-01/network/virtualnetworkpeerings.go#L124-L138

We should ensure that response bodies are always closed when calling Azure api via the sdk.

**Comment by xh3b4sd** [comment]
Do we want to make a project out of this and sort it together within a week or two?

**Comment by TheoBrigitte** [comment]
I can dedicate 1h to a test how much work this is.

1. Find methods in sdk which do not ensure that body is closed.
2. List places where we make use of those methods in azure-operator.

**Comment by xh3b4sd** [comment]
That sounds good. Should we pair on this a bit or join forces somehow?

**Comment by xh3b4sd** [comment]
WDYT, should we pair on this or how can we kick tires here?

**Comment by TheoBrigitte** [comment]
Yeah let's pair on this one

**Comment by xh3b4sd** [comment]
When would you prefer? Spontaneously or with calendar event?

**Comment by TheoBrigitte** [comment]
Not much time this week, how about friday ?

**Comment by xh3b4sd** [comment]
Whatever suits you best. Let's have something in the calendar and we crush it together.

**Comment by xh3b4sd** [comment]
We captured a screenshot where clear upward trends are visible. With our fixes we actually expect these trends to be straightened out. 

<img width="1920" alt="screen shot 2018-11-23 at 14 16 00" src="https://user-images.githubusercontent.com/552769/48947192-a1fd4980-ef30-11e8-9824-80685f423982.png">

**Comment by TheoBrigitte** [comment]
Here is another screenshot after 3 days running 3 tenant clusters. Trends is still going upwards.

<img width="1213" alt="screenshot 2018-11-26 at 10 54 05" src="https://user-images.githubusercontent.com/6536819/49009990-e0ca1400-f169-11e8-9bc7-a73338c6af6f.png">

**Comment by xh3b4sd** [comment]
It looks like it is stabilizing over time. At least this issue here should be closed when the PR is merged. We did the thing. When we get more real memory leak issues we can address them separately.

**Comment by tuommaki** [comment]
FYI: In case someone is investigating this further one day, there's debug server enabled (https://github.com/giantswarm/azure-operator/blob/master/helm/azure-operator-chart/templates/configmap.yaml#L8-L11) so doing `kubectl port-forward` to debug server and grabbing profiling dump may help to dig further: https://golang.org/pkg/net/http/pprof/

**Comment by TheoBrigitte** [comment]
Closing as PR was merged.
