### ISSUE TITLE
use parent template URI for nested templates

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/azure-operator#35]
Let's check if it is possible to reuse `main.json` template URI and not pass full URIs as a parameter.

Source https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-deployment

```
"variables": {  
    "sharedTemplateUrl": "[uri(deployment().properties.templateLink.uri, 'shared-resources.json')]"  
}
```

**Comment by xh3b4sd** [comment]
Isn't this done already?

**Comment by kopiczko** [comment]
Not yet.

**Comment by kopiczko** [comment]
I don't think there is a reason to keep that open. I think we'll have to do it when it turns out the development is too slow, we can't handle errors really well, or we need to split templates to do reconciliation properly.
