### ISSUE TITLE
Create ARM template resource

### ISSUE THREAD

**Issue by rossf7** [giantswarm/azure-operator#6]
* We want to use Azure [Resource Manager](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview#template-deployment) (ARM) templates for managing Azure resources.
* We should add an ARM template resource using the operatorkit framework that allows multiple templates to be run.
* To run the templates we need to create a deployment using the Go SDK.

See https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/resources/resources#DeploymentsClient.CreateOrUpdate

**Comment by kopiczko** [comment]
I didn't manage to do anything useful this week. We can't use Azure API w/o more privileges. Details: https://gigantic.slack.com/archives/C5WMGMRL7/p1503507738000658

**Comment by kopiczko** [comment]
This looks like a good sample: https://github.com/Azure-Samples/resource-manager-go-resources-and-groups

**Comment by rossf7** [comment]
The deployment resource is implemented and calls the main template. This uses linked templates to call the child templates. For now, we're using GitHub for hosting the templates so we can iterate on the template dev.
